<?php

/**
 * @file
 * Install, update, and uninstall functions for the Enacast module.
 */

/**
 * Implements hook_field_schema().
 */
function enacast_field_schema($field) {

  switch ($field['type']) {
    case 'enacast_program':
      $columns = array(
        'value' => array(
          'type' => 'varchar',
          'length' => 255,
          'not null' => FALSE
        ),
      );
      break;

    case 'enacast_radio':
      $columns = array(
        'value' => array(
          'type' => 'varchar',
          'length' => 255,
          'not null' => FALSE
        ),
      );
      break;

    case 'enacast_podcast':
      $columns = array(
        'value' => array(
          'type' => 'int',
          'not null' => FALSE
        ),
        'start' => array(
          'type' => 'int',
          'not null' => FALSE,
          'default' => 0,
        ),
      );
      break;
  }
  return array(
    'columns' => $columns,
  );
}


/**
 * Implementation of hook_schema().
 */
function enacast_schema() {
  $schema['enacast_podcasts'] = array(
    'description' => 'Base table for podcasts imported by Enacast',
    'fields' => array(
      'nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'id'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'pkid'=> array(
        'type'=> 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'name'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'summary'=> array(
        'type'=> 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'audio'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'program_codename'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'program_name'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'radio_codename'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'radio_name'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'utc_datetime'=> array(
        'type'=> 'datetime',
        'not null' => TRUE,
      ),
      'datetime_tz'=> array(
        'type'=> 'datetime',
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );
  $schema['enacast_markers'] = array(
    'description' => 'Markers for Enacasts podcasts',
    'fields' => array(
      'pid'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'pkid'=> array(
        'type'=> 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'mid'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'descr'=> array(
        'type'=> 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'startsecond' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('mid'),
  );
  return $schema;
}

/**
 * Add new column "start" to enacast_podcast fields
 *
 */
function enacast_update_1200() {
  $fields = field_read_fields(array('type' => 'enacast_podcast'));
  foreach ($fields as $field_name => $field) {
    $schema = array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
    );
    if (db_table_exists('field_data_' . $field_name)) {
      db_add_field('field_data_' . $field_name, 'start', $schema);
    }
    if (db_table_exists('field_revision_' . $field_name)) {
      db_add_field('field_revision_' . $field_name, 'start', $schema);
    }
  }
}
